- name: Onboard workers.
  gather_facts: false
  hosts: all
  tasks:

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Clone Git repository
      git:
        repo: "https://github.com/lukesturgis/covid-internet-controls"
        dest: /covid

    - name: Build Docker image
      command: docker build -t worker /covid/worker

    - name: Run Docker container
      docker_container:
        name: worker
        image: worker
        state: started
        detach: yes
        restart_policy: always
        published_ports: 42075:42075