- hosts: all
  gather_facts: false
  vars_files:
    - .env

  tasks:


    # User configuration
    - name: Change root password
      user: name=root password="{{ ROOT_PASSWORD }}"

    - name: Create .ssh directory
      file:
        path: /root/.ssh
        state: directory
        mode: 0700

    - name: Add authorized keys
      copy:
        src: authorized_keys
        dest: /root/.ssh/authorized_keys
        mode: "0644"


    # apt
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: "yes"
    
    - name: Install Docker
      apt:
        name: docker.io
        state: present


    # software installation & build
    - name: Clone Git repository
      git:
        repo: "https://github.com/lukesturgis/covid-internet-controls"
        dest: /src
        accept_hostkey: yes
      register: gitclone

    - name: Copy over .env file for worker
        copy:
          src: .worker.env
          dest: /src/worker
          mode: "0400"
          
    - name: Build Docker image
      command: docker build -t worker /src/worker
      when: gitclone.changed

    - name: Run Docker container
      docker_container:
        name: worker
        image: worker
        state: started
        detach: yes
        restart_policy: always
        published_ports: 42075:42075
      when: gitclone.changed